# Original 26_figs_all.R class-composition and TG-ALR logic, rendered without plot titles.
suppressPackageStartupMessages({library(vroom);library(dplyr);library(tidyr);library(stringr);library(ggplot2);library(patchwork);library(scales);library(grid)})
root <- '/Users/nirwantandukar/Documents/Github/SoLD_paper'; out <- '/Users/nirwantandukar/Documents/Github/SAP-Lipidomics-Database/fig/new_figures/SuppFig_Class_Composition_ALR.png'
class_colors <- c(PC='#00441B',PA='#1B7837',PE='#41AB5D',LPC='#66C2A4',LPE='#2CA25F',PG='#78C679',PS='#C2E699',DG='#54278F',DGDG='#F768A1',MG='#8941ED',MGDG='#FBB4D9',SQDG='#9D4D6C',TG='#ED804A')
classes <- names(class_colors)
read_x <- function(path, cond) vroom(path,show_col_types=FALSE) |> select(-c(2,3,4)) |> rename(Compound_Name=1) |> mutate(Condition=cond)
ctl <- read_x(file.path(root,'data/SPATS_fitted/non_normalized_intensities/Final_subset_control_all_lipids_fitted_phenotype_non_normalized.csv'),'Control'); lin <- read_x(file.path(root,'data/SPATS_fitted/non_normalized_intensities/Final_subset_lowinput_all_lipids_fitted_phenotype_non_normalized.csv'),'LowInput')
classsum <- function(df,label) { pat <- paste0('^(',paste(classes[order(nchar(classes),decreasing=TRUE)],collapse='|'),')(?=\\()'); df |> select(-Condition) |> pivot_longer(-Compound_Name,names_to='Lipid',values_to='Intensity') |> mutate(Class=str_extract(Lipid,pat)) |> filter(!is.na(Class)) |> group_by(Sample=Compound_Name,Class) |> summarise(sum_int=sum(as.numeric(Intensity),na.rm=TRUE),.groups='drop') |> mutate(Condition=label) |> group_by(Sample,Condition) |> mutate(pct=100*sum_int/sum(sum_int,na.rm=TRUE)) |> ungroup() |> filter(nchar(Sample)>=5) }
pct <- bind_rows(classsum(ctl,'Control'),classsum(lin,'LowInput')); means <- pct |> group_by(Condition,Class) |> summarise(pct_mean=mean(pct),.groups='drop'); fmt_pct <- function(x) ifelse(x < .05, '<0.1%', sprintf('%.1f%%', x)); labels <- means |> pivot_wider(names_from=Condition,values_from=pct_mean,values_fill=0) |> mutate(label=paste0(Class,' (C ',fmt_pct(Control),', L ',fmt_pct(LowInput),')')); label_map <- setNames(labels$label,labels$Class); lev <- sort(unique(means$Class)); means <- means |> mutate(Class=factor(Class,levels=lev))
p_a <- ggplot(means,aes(pct_mean,Condition,fill=Class))+geom_col(width=.7,colour='white',linewidth=.3)+geom_text(aes(label=ifelse(pct_mean>=3,sprintf('%.1f%%',pct_mean),'')),position=position_stack(vjust=.5),colour='white',size=3.5,fontface='bold')+scale_fill_manual(values=class_colors[lev],breaks=lev,labels=label_map[lev])+scale_x_continuous(expand=c(0,0),breaks=seq(0,100,25),labels=~paste0(.x,'%'))+labs(x='% of TIC (mean across samples)',y=NULL)+theme_minimal(base_size=12)+theme(legend.position='right',legend.text=element_text(size=9),legend.key.size=unit(.4,'cm'),axis.text=element_text(color='black',size=11),axis.title=element_text(face='bold'),panel.grid.major.y=element_blank(),axis.line=element_line(color='black',linewidth=.5))
wide <- pct |> select(Sample,Condition,Class,pct) |> pivot_wider(names_from=Class,values_from=pct,values_fill=0); m <- as.matrix(wide[,setdiff(names(wide),c('Sample','Condition'))])/100; for(i in seq_len(nrow(m))){x<-m[i,]; if(any(x==0)){z<-x[x>0];x[x==0]<-min(z)*.5};m[i,]<-x/sum(x)}; ref <- 'TG'; nums <- setdiff(colnames(m),ref); alr <- log(sweep(m[,nums,drop=FALSE],1,m[,ref],'/')); set.seed(1201); effect <- colMeans(alr[wide$Condition=='LowInput',])-colMeans(alr[wide$Condition=='Control',]); boot <- replicate(500,{a<-sample(which(wide$Condition=='Control'),sum(wide$Condition=='Control'),TRUE);b<-sample(which(wide$Condition=='LowInput'),sum(wide$Condition=='LowInput'),TRUE);colMeans(alr[b,,drop=FALSE])-colMeans(alr[a,,drop=FALSE])}); alr_tbl <- tibble(Class=colnames(alr),Effect=effect,CI_Low=apply(boot,1,quantile,.025),CI_High=apply(boot,1,quantile,.975)) |> mutate(Class=factor(Class,levels=rev(Class[order(abs(Effect),decreasing=TRUE)])))
p_b <- ggplot(alr_tbl,aes(Class,Effect,color=Class))+geom_hline(yintercept=0,linetype='dashed',color='grey45')+geom_errorbar(aes(ymin=CI_Low,ymax=CI_High),width=.2)+geom_point(size=2.2)+coord_flip()+scale_color_manual(values=class_colors)+labs(x=NULL,y='ALR contrast (LowInput - Control)')+theme_minimal(base_size=12)+theme(legend.position='none',axis.text=element_text(color='black',size=10),axis.title=element_text(face='bold'),panel.grid.major.y=element_blank(),axis.line=element_line(color='black',linewidth=.5))
fig <- (p_a+p_b)+plot_annotation(tag_levels='A',theme=theme(plot.tag=element_text(face='bold',size=16)));dir.create(dirname(out),recursive=TRUE,showWarnings=FALSE);ggsave(out,fig,width=15,height=7,units='in',dpi=300,bg='white')
