suppressPackageStartupMessages({library(readr);library(dplyr);library(stringr);library(ggplot2);library(patchwork)})
repo <- '/Users/nirwantandukar/Documents/Github/SAP-Lipidomics-Database'
in_dir <- file.path(repo,'data/LD_mapped/go_enrichment')
outfile <- file.path(repo,'fig/new_figures/SuppFig_GO_Enrichment_Class_Sums_Ratios.png')
plot_theme <- theme_minimal(base_size=14)+theme(axis.text=element_text(colour='black',size=11),axis.title=element_text(face='bold',size=14),axis.line=element_line(colour='black',linewidth=.5),panel.grid=element_blank(),legend.title=element_text(size=12),legend.text=element_text(size=11),plot.margin=margin(12,100,12,12),plot.tag=element_text(face='bold',size=16),plot.tag.position=c(0,1))
read_go <- function(cond) read_tsv(file.path(in_dir,paste0(cond,'_sumratio_GO_BP_enrichment_LD.tsv')),show_col_types=FALSE) |> filter(p_value<.05) |> mutate(Condition=cond,Term=str_wrap(go_term,44),BH=p_adj_bh<.05,score=-log10(p_adj_bh))
d <- bind_rows(read_go('CTL'),read_go('LIN'))
panel <- function(x,tag) {x <- x |> arrange(desc(BH),p_adj_bh,go_term) |> mutate(y_id=row_number());ggplot(x,aes(score,y_id))+geom_segment(aes(x=0,xend=score,y=y_id,yend=y_id),colour='grey78',linewidth=.45)+geom_point(aes(fill=BH,size=term_test_count),shape=21,colour='black',stroke=.25)+geom_text(aes(label=sprintf('raw p=%s; FDR (BH)=%s',formatC(p_value,format='e',digits=1),formatC(p_adj_bh,format='e',digits=1))),hjust=-.08,size=3)+geom_vline(xintercept=-log10(.05),linetype='dashed',colour='#0072B2',linewidth=.7)+scale_fill_manual(values=c('FALSE'='#E69F00','TRUE'='#009E73'),labels=c('Nominal only','BH-significant'))+scale_size_continuous(range=c(2.8,7),guide='none')+scale_y_continuous(breaks=x$y_id,labels=x$Term,expand=expansion(mult=c(.03,.03)))+scale_x_continuous(expand=expansion(mult=c(.02,.65)))+labs(x=expression(-log[10]*'(FDR-adjusted p)'),y=NULL,fill=NULL,tag=tag)+plot_theme+coord_cartesian(clip='off')}
fig <- (panel(filter(d,Condition=='CTL'),'A') | panel(filter(d,Condition=='LIN'),'B')) + plot_layout(guides='collect') & theme(legend.position='bottom', legend.direction='horizontal')
ggsave(outfile,fig,width=17,height=max(8,.45*max(table(d$Condition))+4),dpi=350,bg='white')
