suppressPackageStartupMessages({library(readr);library(dplyr);library(stringr);library(forcats);library(ggplot2);library(patchwork);library(scales)})
base_dir <- '/Users/nirwantandukar/Documents/Github/SAP-Lipidomics-Database'
in_dir <- file.path(base_dir,'data/LD_mapped/go_enrichment')
out_dir <- file.path(base_dir,'fig/new_figures')
plot_theme <- theme_minimal(base_size=14)+theme(axis.text=element_text(colour='black',size=11),axis.title=element_text(face='bold',size=14),axis.line=element_line(colour='black',linewidth=.5),panel.grid=element_blank(),legend.title=element_text(size=12),legend.text=element_text(size=11),plot.margin=margin(10,110,10,28),plot.tag=element_text(face='bold',size=16),plot.tag.position=c(0,1))
read_go <- function(condition,layer) read_tsv(file.path(in_dir,paste0(condition,'_',layer,'_GO_BP_enrichment_LD.tsv')),show_col_types=FALSE) |> mutate(Condition=condition,Layer=layer,BH_Significant=p_adj_bh<.05,Term=str_wrap(go_term,40))
ctl_i <- read_go('CTL','individual'); lin_i <- read_go('LIN','individual'); ctl_s <- read_go('CTL','sumratio'); lin_s <- read_go('LIN','sumratio')
make_panel <- function(d, tag, allow_nominal=FALSE) {
  if(allow_nominal) d <- bind_rows(d |> slice_min(p_value,n=7,with_ties=FALSE), d |> filter(go_term=='cellular response to phosphate starvation')) |> distinct(go_id,.keep_all=TRUE) else d <- d |> filter(BH_Significant) |> slice_max(fold_enrichment,n=10,with_ties=FALSE)
  d <- d |> arrange(fold_enrichment) |> mutate(Term=factor(Term,levels=Term), Status=ifelse(BH_Significant,'BH-significant','Nominal only'))
  ggplot(d,aes(fold_enrichment,Term))+
    geom_segment(aes(x=1,xend=fold_enrichment,y=Term,yend=Term),colour='grey75',linewidth=.55)+
    geom_point(aes(fill=Status,size=term_test_count),shape=21,colour='black',stroke=.3)+
    geom_label(aes(label=sprintf('raw p = %s\nBH = %s',formatC(p_value,format='e',digits=1),formatC(p_adj_bh,format='e',digits=1))),hjust=-.08,size=2.8,label.size=.15,fill='white')+
    scale_fill_manual(values=c('BH-significant'='#009E73','Nominal only'='#E69F00'))+
    scale_size_continuous(range=c(3.2,7),guide='none')+
    scale_x_continuous(expand=expansion(mult=c(.02,.85)))+coord_cartesian(clip='off')+
    labs(x='Fold enrichment',y=NULL,tag=tag,fill=NULL)+plot_theme+theme(legend.position='bottom',axis.text.y=element_text(size=9))
}
# Individual: LIN is shown as top nominal terms because no term passes BH correction.
p_ind <- (make_panel(ctl_i,'A',FALSE)|make_panel(lin_i,'B',TRUE)) +
  plot_layout(guides='collect') &
  theme(legend.position='bottom',legend.direction='horizontal',legend.justification='center')
ggsave(file.path(out_dir,'SuppFig_GO_Enrichment_Individual_Lipids.png'),p_ind,width=15,height=7,dpi=350,bg='white')
# The combined class-sum/class-ratio plot is generated by script 27 so it can
# retain nominal terms and display BH-FDR status without being overwritten here.
