# Original 26_figs_all.R species-count logic, rendered without plot titles/subtitles.
suppressPackageStartupMessages({library(vroom);library(dplyr);library(tidyr);library(stringr);library(ggplot2);library(patchwork)})
root <- '/Users/nirwantandukar/Documents/Github/SoLD_paper'; out <- '/Users/nirwantandukar/Documents/Github/SAP-Lipidomics-Database/fig/new_figures/SuppFig_Lipid_Species_Counts.png'; cols <- c(PC='#00441B',PA='#1B7837',PE='#41AB5D',LPC='#66C2A4',LPE='#2CA25F',PG='#78C679',PS='#C2E699',DG='#54278F',DGDG='#F768A1',MG='#8941ED',MGDG='#FBB4D9',SQDG='#9D4D6C',TG='#ED804A'); cond_cols <- c(Control='#440154FF',LowInput='#FDE725FF')
read_x <- function(path) {x<-vroom(path,show_col_types=FALSE);names(x)[1]<-'Compound_Name';x}; ctl<-read_x(file.path(root,'data/SPATS_fitted/non_normalized_intensities/Final_subset_control_all_lipids_fitted_phenotype_non_normalized.csv'));lin<-read_x(file.path(root,'data/SPATS_fitted/non_normalized_intensities/Final_subset_lowinput_all_lipids_fitted_phenotype_non_normalized.csv')); get_class<-function(x){z<-str_extract(x,'^[A-Za-z0-9]+(?=\\()');ifelse(z %in% names(cols),z,'Other')}; a<-names(ctl)[grepl('\\(',names(ctl))];b<-names(lin)[grepl('\\(',names(lin))];common<-intersect(a,b);total<-tibble(Category=factor(c('Control Total','LowInput Total','Common','Control Only','LowInput Only'),levels=c('Control Total','LowInput Total','Common','Control Only','LowInput Only')),Count=c(length(a),length(b),length(common),length(setdiff(a,b)),length(setdiff(b,a))),Type=c('Total','Total','Overlap','Unique','Unique'))
theme_fig<-theme_minimal(base_size=12)+theme(axis.text=element_text(color='black',size=11),axis.title=element_text(face='bold'),axis.line=element_line(color='black',linewidth=.5))
p_a<-ggplot(total,aes(Category,Count,fill=Type))+geom_col(width=.7,color='black')+geom_text(aes(label=Count),vjust=-.3,fontface='bold')+scale_fill_manual(values=c(Total='#440154FF',Overlap='#21908CFF',Unique='#FDE725FF'))+scale_y_continuous(expand=expansion(mult=c(0,.1)))+labs(x=NULL,y='Number of Species')+theme_fig+theme(axis.text.x=element_text(angle=30,hjust=1),legend.position='top',panel.grid.major.x=element_blank())
count_cls<-function(z,nm)tibble(Lipid=z,Class=get_class(z)) |> count(Class,name='Count') |> mutate(Condition=nm); cc<-bind_rows(count_cls(a,'Control'),count_cls(b,'LowInput')) |> filter(Class!='Other');ord<-cc |> group_by(Class)|>summarise(T=sum(Count))|>arrange(desc(T))|>pull(Class);cc$Class<-factor(cc$Class,levels=rev(ord));p_b<-ggplot(cc,aes(Class,Count,fill=Condition))+geom_col(position=position_dodge(.8),width=.7,color='black')+geom_text(aes(label=Count),position=position_dodge(.8),hjust=-.2,size=3)+coord_flip()+scale_fill_manual(values=cond_cols)+scale_y_continuous(expand=expansion(mult=c(0,.15)))+labs(x=NULL,y='Number of Species')+theme_fig+theme(legend.position='top',panel.grid.major.y=element_blank())
info<-vroom(file.path(root,'data/lipid_class/final_lipid_classes.csv'),show_col_types=FALSE)|>transmute(Lipid=Lipids,SuperClass=Class);cnt_super<-function(z,nm)tibble(Lipid=z)|>left_join(info,by='Lipid')|>mutate(SuperClass=ifelse(is.na(SuperClass),'Unclassified',SuperClass))|>count(SuperClass,name='Count')|>mutate(Condition=nm);sc<-bind_rows(cnt_super(a,'Control'),cnt_super(b,'LowInput'));so<-sc|>group_by(SuperClass)|>summarise(T=sum(Count))|>arrange(desc(T))|>pull(SuperClass);sc$SuperClass<-factor(sc$SuperClass,levels=rev(so));p_d<-ggplot(sc,aes(SuperClass,Count,fill=Condition))+geom_col(position=position_dodge(.8),width=.7,color='black')+geom_text(aes(label=Count),position=position_dodge(.8),hjust=-.2,size=3)+coord_flip()+scale_fill_manual(values=cond_cols)+scale_y_continuous(expand=expansion(mult=c(0,.15)))+labs(x=NULL,y='Number of Species')+theme_fig+theme(legend.position='top',panel.grid.major.y=element_blank())
# Keep the superclass panel centered below the two upper panels.
fig <- (p_a + p_b + plot_layout(widths = c(1, 1.3))) /
  (plot_spacer() + p_d + plot_spacer() + plot_layout(widths = c(0.15, 1.3, 0.15))) +
  plot_annotation(tag_levels='A',theme=theme(plot.tag=element_text(face='bold',size=16)))
dir.create(dirname(out),recursive=TRUE,showWarnings=FALSE)
ggsave(out,fig,width=14,height=12,units='in',dpi=300,bg='white')
